version: "3.8"

services:
  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    ports:
      - 8333
    volumes:
      - bitcoin-core-data:/data
    networks:
      - bitcoin
    environment:
      NETWORK: mainnet

  bitcoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    ports:
      - 8000
      - 9000
    volumes:
      - blockbook-data:/data
      - ./configs/blockbook-bitcoin.json:/chaincfg.json
    networks:
      - bitcoin
    configs:
      - source: blockbook-bitcoin
        target: /chaincfg.json
        mode: 0444
    entrypoint: ["/bin/sh", "-c", "cd /go/src/github.com/trezor/blockbook/; exec /go/src/github.com/trezor/blockbook/blockbook -sync -blockchaincfg /chaincfg.json -datadir /data -internal :9000 -public :8000 -log_dir /log"]
  
volumes:
  bitcoin-core-data:
    driver: local
  blockbook-data:
    driver: local
  

networks:
  bitcoin:
  monacoin:
  bitzeny:
  zcash:

configs:
  blockbook-bitcoin:
    file: ./configs/blockbook-bitcoin.json