version: "3.8"

services:
  envoy:
    image: ghcr.io/yuki-js/ouchistack/envoy:latest
    ports:
      - "8080:80"
    networks:
      - envoy
    configs:
      - source: envoy
        target: /etc/envoy/envoy.yaml
    deploy:
      replicas: 2

  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    ports:
      - "8333:8333" # P2P
    volumes:
      - /ouchistack-data/hdd/bitcoin-core-data:/data
    networks:
      - bitcoin
    environment:
      NETWORK: mainnet
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  bitcoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    command: ["-workers=1", "-dbcache=0"]
    volumes:
      - /ouchistack-data/hdd/bitcoin-blockbook-data:/data
    networks:
      - bitcoin
      - envoy
    configs:
      - source: blockbook-bitcoin
        target: /chaincfg.json
        mode: 0444
    depends_on:
      - bitcoin-core
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "4G"
    stop_grace_period: 5m

  cors-proxy:
    image: ghcr.io/yuki-js/ouchistack/cors-proxy:latest
    networks:
      - envoy
    deploy:
      replicas: 2

  monacoin-core:
    image: ghcr.io/yuki-js/ouchistack/monacoin-core:latest
    volumes:
      - /ouchistack-data/hdd/monacoin-core-data:/data
    networks:
      - monacoin
    environment:
      NETWORK: mainnet
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  monacoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    command: ["-workers=1", "-dbcache=0"]
    volumes:
      - /ouchistack-data/hdd/monacoin-blockbook-data:/data
    networks:
      - monacoin
      - envoy
    configs:
      - source: blockbook-monacoin
        target: /chaincfg.json
        mode: 0444
    depends_on:
      - monacoin-core
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    stop_grace_period: 1m

  geth:
    image: ghcr.io/yuki-js/ouchistack/geth:latest
    volumes:
      - /ouchistack-data/ssd/geth:/root/.ethereum
    networks:
      - eth
      - envoy
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname==iwashi"
      resources:
        limits:
          cpus: "2.0"
          memory: "8G"
    stop_grace_period: 5m

  openethereum:
    image: openethereum/openethereum:latest
    volumes:
      - /ouchistack-data/hdd/openethereum:/home/openethereum/.local/share/
    command:
      - "--chain=ethereum"
      - "--unsafe-expose"
      - "--jsonrpc-hosts=all"
      - "--jsonrpc-cors=all"
      - "--max-peers=48"
      - "--snapshot-peers=8"
      - "--scale-verifiers" # add
      - "--cache-size-db=8192" # add
      - "--cache-size-blocks=256" # add
      - "--cache-size-queue=4096" # add
      - "--cache-size-state=4096" # add
      - "--num-verifiers=64" # add
    networks:
      - eth
      - envoy
    deploy:
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname==disabled"

  bitzeny-core:
    image: ghcr.io/yuki-js/ouchistack/bitzeny:latest
    ports:
      - "8334:8333" # P2P
    volumes:
      - /ouchistack-data/hdd/bitzeny-core-data:/data
    networks:
      - bitzeny
    environment:
      NETWORK: mainnet
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "4G"

  bitzeny-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    command: ["-workers=1", "-dbcache=0"]
    volumes:
      - /ouchistack-data/hdd/bitzeny-blockbook-data:/data
    networks:
      - bitzeny
      - envoy
    configs:
      - source: blockbook-bitzeny
        target: /chaincfg.json
        mode: 0444
    depends_on:
      - bitzeny-core
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "4G"
    stop_grace_period: 5m
  lnd:
    image: ghcr.io/yuki-js/ouchistack/lnd:latest
    volumes:
      - /ouchistack-data/ssd/lnd-data:/data
    networks:
      - lnd
      - bitcoin
    environment:
      NETWORK: mainnet
      RPCPASS: rpcpass
    depends_on:
      - bitcoin-core
    ports:
      - 9735:9735
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "4G"

networks:
  bitcoin:
  envoy:
  monacoin:
  eth:
  bitzeny:

configs:
  blockbook-bitcoin:
    file: ./configs/blockbook-bitcoin.json
  envoy:
    file: ./configs/envoy.yaml
  blockbook-monacoin:
    file: ./configs/blockbook-monacoin.json
  blockbook-bitzeny:
    file: ./configs/blockbook-bitzeny.json
