version: "3.8"

services:
  envoy:
    image: ghcr.io/yuki-js/ouchistack/envoy:latest
    ports:
      - "80:80" # Service port to upstream proxy
      - "10000:10000" # admin
    networks:
      - envoy
    configs:
      - source: envoy
        target: /etc/envoy/envoy.yaml

  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    ports:
      - "8333:8333" # P2P
    volumes:
      - /ouchistack-data/hdd/bitcoin-core-data:/data
    networks:
      - bitcoin
    environment:
      NETWORK: mainnet
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  bitcoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    ports:
      - "9000:9000" # internal
    volumes:
      - /ouchistack-data/hdd/bitcoin-blockbook-data:/data
    networks:
      - bitcoin
      - envoy
    configs:
      - source: blockbook-bitcoin
        target: /chaincfg.json
        mode: 0444
    depends_on:
      - bitcoin-core
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "4G"

  cors-proxy:
    image: ghcr.io/yuki-js/ouchistack/cors-proxy:latest
    networks:
      - envoy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "300M"

networks:
  bitcoin:
  envoy:

configs:
  blockbook-bitcoin:
    file: ./configs/blockbook-bitcoin.json
  envoy:
    file: ./configs/envoy.yaml
