version: "3"

services:
  btcd:
    image: ghcr.io/yuki-js/ouchistack/btcd:latest
    volumes:
      - shared:/rpc
      - btcd:/data
    environment:
      - RPCUSER=a
      - RPCPASS=a
      - NETWORK=mainnet
      - DEBUG=info
      - MINING_ADDRESS
    entrypoint: ["bash", "./start-btcd.sh"]
    ports:
      - 8334
      - 8333
  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    # specify additional command line arguments here
    command: bitcoind
    ports:
      # change to 18333 if running testnet
      - 8333
volumes:
  shared:
    driver: local
  btcd:
    driver: local
  bitcoind:
    driver: local