version: "3.8"

services:
  envoy:
    image: ghcr.io/yuki-js/ouchistack/envoy:latest
    ports:
      - "443:443"
      - "9000"
    configs:
      - source: envoy
        target: /etc/envoy/envoy.yaml
    networks:
      - bitcoin
  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    command: "-connect=192.168.0.3:49158"
    ports:
      - 8333
    volumes:
      - /ouchistack-data/hdd/bitcoin-core-data:/data
    networks:
      - bitcoin
    environment:
      NETWORK: mainnet

  bitcoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    ports:
      - 8000
    volumes:
      - /ouchistack-data/hdd/blockbook-data:/data
    networks:
      - bitcoin
    configs:
      - source: blockbook-bitcoin
        target: /chaincfg.json
        mode: 0444
networks:
  bitcoin:

configs:
  blockbook-bitcoin:
    file: ./configs/blockbook-bitcoin.json
  envoy:
    file: ./configs/envoy.yml
