version: "3.8"

services:
  envoy:
    image: ghcr.io/yuki-js/ouchistack/envoy:latest
    ports:
      - "80:80"
      - "10000"
    networks:
      - envoy
    configs:
      - source: envoy
        target: /etc/envoy/envoy.yaml

  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    ports:
      - 8333
    volumes:
      - /ouchistack-data/hdd/bitcoin-core-data:/data
    networks:
      - bitcoin
    environment:
      NETWORK: mainnet
    deploy:
      placement:
        max_replicas_per_node: 1

  bitcoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    ports:
      - 8000
    volumes:
      - /ouchistack-data/hdd/bitcoin-blockbook-data:/data
    networks:
      - bitcoin
      - envoy
    configs:
      - source: blockbook-bitcoin
        target: /chaincfg.json
        mode: 0444
    depends_on:
      - bitcoin-core
    deploy:
      placement:
        max_replicas_per_node: 1

  cors-proxy:
    image: ghcr.io/yuki-js/ouchistack/cors-proxy:latest
    networks:
      - envoy
    depends_on:
      - envoy

networks:
  bitcoin:
  envoy:

configs:
  blockbook-bitcoin:
    file: ./configs/blockbook-bitcoin.json
  envoy:
    file: ./configs/envoy.yaml

secrets:
  cert-chain:
    external: true
  private-key:
    external: true
