version: "3"

services:
  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    ports:
      - 8333
    volumes:
      - bitcoin-core-data:/data

volumes:
  bitcoin-core-data:
    driver: local
  

networks:
  bitcoin:
  monacoin:
  bitzeny:
  zcash:
    