version: "3.8"

services:
  envoy:
    image: ghcr.io/yuki-js/ouchistack/envoy:latest
    ports:
      - "80:80"
    networks:
      - envoy
    configs:
      - source: envoy
        target: /etc/envoy/envoy.yaml

  bitcoin-core:
    image: ghcr.io/yuki-js/ouchistack/bitcoin-core:latest
    ports:
      - "8333:8333" # P2P
    volumes:
      - /ouchistack-data/hdd/bitcoin-core-data:/data
    networks:
      - bitcoin
    environment:
      NETWORK: mainnet
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  bitcoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    volumes:
      - /ouchistack-data/hdd/bitcoin-blockbook-data:/data
    networks:
      - bitcoin
      - envoy
    configs:
      - source: blockbook-bitcoin
        target: /chaincfg.json
        mode: 0444
    depends_on:
      - bitcoin-core
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "4G"
    stop_grace_period: 30s

  cors-proxy:
    image: ghcr.io/yuki-js/ouchistack/cors-proxy:latest
    networks:
      - envoy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "300M"

  monacoin-core:
    image: ghcr.io/yuki-js/ouchistack/monacoin-core:latest
    volumes:
      - /ouchistack-data/hdd/monacoin-core-data:/data
    networks:
      - monacoin
    environment:
      NETWORK: mainnet
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"
  monacoin-blockbook:
    image: ghcr.io/yuki-js/ouchistack/blockbook:latest
    volumes:
      - /ouchistack-data/hdd/monacoin-blockbook-data:/data
    networks:
      - monacoin
      - envoy
    configs:
      - source: blockbook-monacoin
        target: /chaincfg.json
        mode: 0444
    depends_on:
      - monacoin-core
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"
  geth:
    image: ghcr.io/yuki-js/ouchistack/geth:latest
    volumes:
      - /ouchistack-data/ssd/geth:/root/.ethereum
    networks:
      - eth
      - envoy
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"

networks:
  bitcoin:
  envoy:
  monacoin:
  eth:

configs:
  blockbook-bitcoin:
    file: ./configs/blockbook-bitcoin.json
  envoy:
    file: ./configs/envoy.yaml
  blockbook-monacoin:
    file: ./configs/blockbook-monacoin.json
