static_resources:
  listeners:
    - name: listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80

      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: btc
                      domains: ["os-btc.missmonacoin.org"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: cl-bitcoin-blockbook
                      cors:
                        allow_origin_string_match: ["*"]
                        allow_methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
                        max_age: 16777216

                    - name: cors-proxy
                      domains: ["os-proxy.missmonacoin.org"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: cl-cors-proxy
                      cors:
                        allow_origin_string_match: ["*"]
                        allow_methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
                        max_age: 16777216
                    - name: mona
                      domains: ["os-mona.missmonacoin.org"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: cl-monacoin-blockbook
                      cors:
                        allow_origin_string_match: ["*"]
                        allow_methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
                        max_age: 16777216

                    - name: eth
                      domains: ["os-eth.missmonacoin.org"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: cl-geth
                      cors:
                        allow_origin_string_match: ["*"]
                        allow_methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
                        max_age: 16777216

  clusters:
    - name: cl-bitcoin-blockbook
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 30s
      load_assignment:
        cluster_name: cl-bitcoin-blockbook
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: bitcoin-blockbook
                      port_value: 8000
    - name: cl-monacoin-blockbook
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 30s
      load_assignment:
        cluster_name: cl-monacoin-blockbook
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: monacoin-blockbook
                      port_value: 8000
    - name: cl-cors-proxy
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 0.25s
      load_assignment:
        cluster_name: cl-cors-proxy
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: cors-proxy
                      port_value: 8080
    - name: cl-geth
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 0.25s
      load_assignment:
        cluster_name: geth
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: geth
                      port_value: 8545
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
